goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.array', 'goog.object', 'goog.string.StringBuffer']);
goog.addDependency("../grow_game/draw_canvas.js", ['grow_game.draw_canvas'], ['cljs.core']);
goog.addDependency("../garden/types.js", ['garden.types'], ['cljs.core']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['cljs.core', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency("../hiccups/runtime.js", ['hiccups.runtime'], ['cljs.core', 'clojure.string']);
goog.addDependency("../cljs/reader.js", ['cljs.reader'], ['cljs.core', 'goog.string']);
goog.addDependency("../cljs/core/async/impl/protocols.js", ['cljs.core.async.impl.protocols'], ['cljs.core']);
goog.addDependency("../cljs/core/async/impl/ioc_helpers.js", ['cljs.core.async.impl.ioc_helpers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/buffers.js", ['cljs.core.async.impl.buffers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/dispatch.js", ['cljs.core.async.impl.dispatch'], ['cljs.core.async.impl.buffers', 'cljs.core']);
goog.addDependency("../cljs/core/async/impl/channels.js", ['cljs.core.async.impl.channels'], ['cljs.core.async.impl.buffers', 'cljs.core', 'cljs.core.async.impl.dispatch', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/timers.js", ['cljs.core.async.impl.timers'], ['cljs.core', 'cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async.js", ['cljs.core.async'], ['cljs.core.async.impl.ioc_helpers', 'cljs.core.async.impl.buffers', 'cljs.core', 'cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core.async.impl.protocols', 'cljs.core.async.impl.timers']);
goog.addDependency("../figwheel/client.js", ['figwheel.client'], ['cljs.core', 'clojure.string', 'cljs.reader', 'cljs.core.async', 'goog.net.jsloader']);
goog.addDependency("../clojure/browser/event.js", ['clojure.browser.event'], ['cljs.core', 'goog.events.EventType', 'goog.events.EventTarget', 'goog.events']);
goog.addDependency("../clojure/browser/net.js", ['clojure.browser.net'], ['goog.net.xpc.CrossPageChannel', 'clojure.browser.event', 'goog.net.xpc.CfgFields', 'cljs.core', 'goog.net.EventType', 'goog.json', 'goog.net.XhrIo']);
goog.addDependency("../clojure/browser/repl.js", ['clojure.browser.repl'], ['clojure.browser.event', 'clojure.browser.net', 'cljs.core']);
goog.addDependency("../garden/util.js", ['garden.util'], ['cljs.core', 'goog.string', 'goog.string.format', 'clojure.string', 'garden.types']);
goog.addDependency("../garden/units.js", ['garden.units'], ['cljs.core', 'garden.util', 'cljs.reader', 'garden.types']);
goog.addDependency("../garden/color.js", ['garden.color'], ['cljs.core', 'garden.util', 'clojure.string']);
goog.addDependency("../garden/compiler.js", ['garden.compiler'], ['garden.units', 'cljs.core', 'garden.util', 'clojure.string', 'garden.types', 'garden.color']);
goog.addDependency("../garden/core.js", ['garden.core'], ['cljs.core', 'garden.compiler']);
goog.addDependency("../grow_game/core.js", ['grow_game.core'], ['goog.Timer', 'cljs.core', 'grow_game.draw_canvas', 'goog.dom', 'figwheel.client', 'hiccups.runtime', 'clojure.browser.repl', 'goog.events', 'garden.core']);